#!/bin/zsh

#trap 'echo BYE && return 1' ERR

function palias () {
    case "$1" in
        list)
            cat ~/.palias
        clean)
            echo "" > ~/.palias
            ;;
        save)
            cd /home/ulysse/Documents/programmes/dotfiles
            #git stash save
            current_branch=`git rev-parse --abbrev-ref HEAD`
            [[ "$current_branch" != quicksave ]] && ( git branch --list | grep -q quicksave ) || git branch quicksave
            [[ "$current_branch" != quicksave ]] && git checkout quicksave
            git add --patch palias
            number=$(git config quicksave.number)
            [[ -z "$number" ]] && git config quicksave.number 0
            let number++
            git commit -m "quiksave $number"
            git config quicksave.number $number
            [[ "$current_branch" != quicksave ]] && git checkout $current_branch
            #git stash apply
            popd > /dev/null
            ;;
        *=*)
            new_alias=`printf "alias %q" "$@"`
            echo $new_alias >> ~./palias
            ;;
        *)
            echo "$0: bad command '$@'."
            return 1
    esac
    return 0
}
