#!/usr/bin/env zsh

branches=(`git branch --no-color --merged | grep -E "^  (fix|feature)"`)

for branch in $branches ;do
    issue=`cut -d- -f2,3 <<<$branch`
    curl -X POST \
      http://jira.s.nuecho.com/rest/api/latest/issue/$issue/transitions \
      -H 'authorization: Basic dWJ1b25vbW86bXVbLm5dZXRANWRlTTBvdTFhdE8u' \
      -H 'content-type: application/json' \
      -d '{"transition": {"id": "31"}}'
    git branch -d $branch
done
